# ~ Copyright: (c) 2011. Turtsevich Alexander
# ~
# ~ Licensed under the MIT license: http://www.opensource.org/licenses/mit-license.html

all: hidapi.jar

android=./android
build.xml=$(android)/build.xml
src=$(android)/src

hidapi.jar: $(src) clean
	ant -f $(build.xml) release
	cp $(android)/bin/classes.jar ./bin/hidapi.jar -f

clean:
	ant -f $(build.xml) clean